### ISSUE TITLE
Where the modifications regarding Mamba are located? 

### ISSUE THREAD

**Issue by JacCubk** [HZAI-ZJNU/Mamba-YOLO#9]
Thank you for the great work you have provided. I have a silly question. I apologize, I am a beginner. I carefully read the code but did not find the code related to mamba. Could you please tell me?

**Comment by EthanW-coder** [comment]
Thanks for your interest in our code, the yaml files are stored in: mamba-yolo/ultralytics/cfg/models/mamba-yolo/
SimpleStem, VSSBlock, VisionClueMerge code files are stored in: ultralytics/nn/modules/mamba_yolo.py

**Comment by JacCubk** [comment]
Thanks a lot!
